---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance-managed-agent-skills-default
    image: "python:3.13-bookworm"
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: /home/zzq/code/repo/lingua-realm/agent-config-ansible/roles
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible